name:                game-of-life
version:             0.1.0.0
github:              "FourCredits/game-of-life"
license:             BSD3
author:              "Erik Grundy"
maintainer:          "erik.grundy@gmail.com"
copyright:           "2021 Erik Grundy"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Game of Life, written in Haskell
category:            Game

description:         Please see the README on GitHub at <https://github.com/FourCredits/game-of-life#readme>

dependencies:
- base >= 4.7 && < 5
- gloss
- array

library:
  source-dirs: src

executables:
  gol:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - game-of-life