name:                game-of-life
version:             0.1.0.0
github:              "FourCredits/game-of-life"
license:             BSD3
author:              "Erik Grundy"
maintainer:          "erik.grundy@gmail.com"
copyright:           "2021 Erik Grundy"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Game of Life, written in Haskell
category:            Game

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/FourCredits/game-of-life#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  gol:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - game-of-life

tests:
  game-of-life-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - game-of-life
